# Generated by Django 5.2 on 2025-05-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEAL_CREATE', 'Создание сделки'), ('CONTACT_UPDATE', 'Обновление контакта'), ('ERROR', 'Ошибка синхронизации')], max_length=20)),
                ('details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
    ]
